### ISSUE TITLE
The menu is not listing in the website. In the restaurantmenu while looping over it .

### ISSUE THREAD

**Issue by Aneeshh18** [samirKeshwani2201/namaste-react#1]
The menu is not listing in the website. In the restaurantmenu while looping over it .

**Comment by Aneeshh18** [comment]
For some restaurant it's showing and for some, it's not.

**Comment by samirKeshwani2201** [comment]
Only the recommended list of items has been displayed of a particular restaurant so some may not have so its not displaying , I have done this because  I think that the api has being changed so I was not able to get the menu
